services:
  app:
    build: 
      context: .
    container_name: app
    networks:
      - node-network
    volumes:
      - ./:/usr/src/app
    tty: true
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql-container
    restart: always
    tty: true
    ports: 
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../databases/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_USER=root - Nas novas versões da imagem do MySQL 5.7, essa variável não é mais aceita, porque o usuário root do banco já é criado por padrão
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
